import type { Config } from 'tailwindcss';

// Design tokens mirror DESIGN.md (source of truth). "Sonic Depth" — premium
// dark mode, purple primary. Stitch layout values are reduced to these tokens
// rather than hardcoded.
export default <Partial<Config>>{
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#131313',
        'on-background': '#e5e2e1',
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#cfc2d5',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#988d9f',
        'outline-variant': '#4c4353',
        'surface-tint': '#ddb8ff',
        primary: '#ddb8ff',
        'on-primary': '#490081',
        'primary-container': '#711eba',
        'on-primary-container': '#dab2ff',
        'inverse-primary': '#8133ca',
        'primary-fixed': '#f0dbff',
        'primary-fixed-dim': '#ddb8ff',
        'on-primary-fixed': '#2c0051',
        'on-primary-fixed-variant': '#6709b0',
        secondary: '#c8c6c5',
        'on-secondary': '#303030',
        'secondary-container': '#474746',
        'on-secondary-container': '#b7b5b4',
        'secondary-fixed': '#e5e2e1',
        'secondary-fixed-dim': '#c8c6c5',
        'on-secondary-fixed': '#1b1c1c',
        'on-secondary-fixed-variant': '#474746',
        tertiary: '#c8c6c6',
        'on-tertiary': '#303030',
        'tertiary-container': '#505050',
        'on-tertiary-container': '#c4c2c2',
        'tertiary-fixed': '#e4e2e2',
        'tertiary-fixed-dim': '#c8c6c6',
        'on-tertiary-fixed': '#1b1c1c',
        'on-tertiary-fixed-variant': '#474747',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        sans: ['Inter Variable', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': [
          '48px',
          { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' },
        ],
        'display-lg-mobile': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '800' },
        ],
        'headline-md': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' },
        ],
        'body-lg': [
          '16px',
          { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' },
        ],
        'body-sm': [
          '14px',
          { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' },
        ],
        'label-caps': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' },
        ],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        gutter: '16px',
        'card-gap': '24px',
        'container-padding': '24px',
        'section-margin': '48px',
      },
    },
  },
};
